PersonelApp.Web/Models/IzinViewModel.cs
using PersonelApp.Web.Entity;

namespace PersonelApp.Web.Models
{
    public class IzinViewModel
    {
        public List<IzinBilgisi> Izinler {  get; set; }

        public List<Personel> Personels { get; set; }

    }
}

PersonelApp.Web/Models/PersonelsViewModel.cs
using System.ComponentModel.DataAnnotations;
using PersonelApp.Web.Entity;

namespace PersonelApp.Web.Models
{
    public class PersonelsViewModel
    {
        public List<PersonelViewModel> personels { get; set; }  
       
    }

    public class PersonelViewModel
    {
        public string Ad {  get; set; }
        public string Soyad { get; set; }
        public DateOnly Zaman { get; set; }
        public int GecenYıl { get; set; }
        public long KimlikNo { get; set; }
        public int BuYıl { get; set; }
        public int PersonelId { get; set; }
        public Fakulte Fakulte { get; set; }
        public Bolum Bolum { get; set; }
        public Abd Abd { get; set; }
    }

    public class FGYEditViewModel
    {
        public int PersonelId { get; set; }
        public int FakulteId { get; set; }
        public Fakulte Fakulte { get; set; }
        public int BolumId { get; set; }
        public Bolum Bolum { get; set; }
        public int AbdId { get; set; }
        public Abd Abd { get; set; }

    }
}

PersonelApp.Web/Controllers/PersonelController.cs
using System.Runtime.CompilerServices;
using AspNetCoreGeneratedDocument;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using PersonelApp.Web.Data;
using PersonelApp.Web.Entity;
using PersonelApp.Web.Models;
using System.Linq;

namespace PersonelApp.Web.Controllers
{
    
    public class PersonelController : Controller
    {
        private readonly PersonelContext _context;
        public PersonelController(PersonelContext context) 
        { 
            _context = context; 
        }
       

        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult List(string q)
        {
            var personel = _context.Personels.AsQueryable();


            ViewBag.Fakultes = new SelectList(_context.Fakultes.ToList(), "FakulteId", "FakulteName");
            ViewBag.Bolums = new SelectList(_context.Bolums.ToList(), "BolumId", "BolumName");
            ViewBag.Abds = new SelectList(_context.Abds.ToList(), "AbdId", "AbdName");


            if (!string.IsNullOrEmpty(q))
            {
                personel = personel.Where(i =>
                i.Ad.ToLower().Contains(q.ToLower()) ||
                i.Soyad.ToLower().Contains(q.ToLower())
                );
            }

            var view = new PersonelsViewModel
            {
                personels = personel
                .Include(p => p.Fakulte)
                .Include(p => p.Bolum)
                .Include(p => p.Abd)
                .Select(f => new PersonelViewModel
                {
                    PersonelId = f.PersonelId,
                    Ad = f.Ad,
                    Soyad = f.Soyad,
                    Zaman = f.Zaman,
                    GecenYıl = f.GecenYıl,
                    BuYıl = f.BuYıl,
                    Fakulte = f.Fakulte,
                    Bolum = f.Bolum,
                    Abd = f.Abd,
                    KimlikNo = f.KimlikNo
                })
                .ToList()
            };



            return View(view);
        }
        [HttpGet]
        public IActionResult Create(int? id) 
        {
            ViewBag.Fakultes= new SelectList(_context.Fakultes.ToList(),"FakulteId","FakulteName");
            ViewBag.Bolums = new SelectList(_context.Bolums.ToList(), "BolumId", "BolumName");
            ViewBag.Abds = new SelectList(_context.Abds.ToList(), "AbdId", "AbdName");
            return View();
        }
        [HttpPost]
        public IActionResult Create(Personel p)
        {
            
                bool KimlikKontrol= _context.Personels.Any(k => k.KimlikNo == p.KimlikNo);

                if (KimlikKontrol)
                {
                    ModelState.AddModelError("KimlikNo", "Bu TC Kimlik Numarası sistemde zaten kayıtlı.");
                    return View(p);
                }
                
                
                int diff1 = DateOnly.FromDateTime(DateTime.Today).Year-p.Zaman.Year;

                if (diff1 == 0)
                {
                    p.GecenYıl = 0;
                    p.BuYıl = 0;
                }
                if (diff1 >=1 && diff1 <=9)
                {
                    p.GecenYıl = 0;
                    p.BuYıl = 20;
                }
                if (diff1 >= 10)
                {
                    p.GecenYıl = 0;
                    p.BuYıl = 30;
                }
                _context.Personels.Add(p);
                _context.SaveChanges();
                TempData["Message"] = $"Yeni Kişi Eklendi.";
                return RedirectToAction("list");
            
            //return View(p);  
        }
        [HttpGet]
        public IActionResult IzinForm(int id)
        {
            var model = new IzinBilgisi
            {
                PersonelId = id,
            };
            return View(model);
        }
        [HttpPost]
        public IActionResult IzinForm(IzinBilgisi i)
        {
            if (((i.BitisTarihi - i.BaslangicTarihi).Days + 1) < 0)
            {
                ModelState.AddModelError("BitisTarihi", "Bitiş tarihi başlangıçtan küçük olamaz.");
                return View(i);
            }
            if (ModelState.IsValid) 
            {

                int diff = (i.BitisTarihi - i.BaslangicTarihi).Days+1;
                i.Kullanilanizin=diff;
                _context.Izinler.Add(i);

                
            }

            var sonuc = _context.Personels.FirstOrDefault(p => p.PersonelId == i.PersonelId);

            if (sonuc != null) 
            {
                if(((sonuc.GecenYıl+sonuc.BuYıl) - i.Kullanilanizin) >= 0)
                {
                    sonuc.GecenYıl = sonuc.GecenYıl - i.Kullanilanizin;

                    if (sonuc.GecenYıl < 0)
                    {
                        int diff2;
                        diff2 = sonuc.GecenYıl * (-1);


                        sonuc.BuYıl = sonuc.BuYıl - diff2;
                        sonuc.GecenYıl = 0;

                    }

                    _context.SaveChanges();
                    TempData["Message"] = $"İzin Eklendi";
                    return RedirectToAction("Izinler");


                }

                if (((sonuc.GecenYıl + sonuc.BuYıl) - i.Kullanilanizin) < 0)
                {
                    ModelState.AddModelError("BitisTarihi", "Yıllık İzin Yetersizdir.");
                    return View(i);
                }



            }

            return View(i);
        }

        public IActionResult Izinler()
        {
            var izin = new IzinViewModel
            {

                Izinler = _context.Izinler.ToList(),
                Personels = _context.Personels.ToList(),
            };

            return View(izin);
        }

        
        [HttpGet]
        public IActionResult Update()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Update(Personel p)
        {
            
            var personel = _context.Personels.ToList();


            foreach (var z in personel)
            {
                z.GecenYıl = z.BuYıl;
                z.BuYıl = 0;

                int diff1 = DateOnly.FromDateTime(DateTime.Today).Year - z.Zaman.Year;

                if (diff1 == 0)
                {
                    z.BuYıl = 0;
                }
                if (diff1 >= 1 && diff1 <= 9)
                {
                    z.BuYıl = 20;
                }
                if (diff1 >= 10)
                {
                    z.BuYıl = 30;
                }
                _context.SaveChanges();
            }
            
            

            return RedirectToAction("List");
        }
        [HttpGet]
        public IActionResult Edit (int id)
        {
            
            return View(_context.Personels.Find(id));
        }
        [HttpPost]
        public IActionResult Edit(Personel p) 
        {
            var sonuc = _context.Personels.FirstOrDefault(i => i.PersonelId == p.PersonelId);

            if (sonuc != null) 
            {
                sonuc.Ad = p.Ad;
                sonuc.Soyad = p.Soyad;
                sonuc.GecenYıl=p.GecenYıl;
                sonuc.BuYıl = p.BuYıl;

                
                _context.SaveChanges();
                return RedirectToAction("List");
            }
            return View(p);
        }
        [HttpPost]
        public IActionResult Delete(int PersonelId) 
        { 
            var delete = _context.Personels.Find(PersonelId);
            _context.Personels.Remove(delete);
            _context.SaveChanges(); 
            return RedirectToAction("List");
        }
        [HttpGet]
        public IActionResult EditFGY(int id)
        {
            var entity = _context.Personels.Include(i => i.Fakulte).Include(i => i.Bolum).Include(i => i.Abd).Select(p=> new FGYEditViewModel
            {
                PersonelId = p.PersonelId,
                FakulteId = p.FakulteId,
                BolumId = p.BolumId,
                AbdId = p.AbdId,
                Fakulte = p.Fakulte,
                Bolum = p.Bolum,
                Abd = p.Abd
            }).FirstOrDefault(p=> p.PersonelId == id);

            ViewBag.Fakultes = new SelectList(_context.Fakultes.ToList(), "FakulteId", "FakulteName");
            ViewBag.Bolums = new SelectList(_context.Bolums.ToList(), "BolumId", "BolumName");
            ViewBag.Abds = new SelectList(_context.Abds.ToList(), "AbdId", "AbdName");
            return View(entity);
        }
        [HttpPost]
        public IActionResult EditFGY(Personel p)
        {
            var sonuc = _context.Personels.Find(p.PersonelId);

            if (sonuc != null)
            {
                sonuc.FakulteId = p.FakulteId;
                sonuc.BolumId = p.BolumId;
                sonuc.AbdId = p.AbdId;

                _context.SaveChanges();
                return RedirectToAction("List");
            }

            return View(p);
        }

        [HttpPost]
        public IActionResult IzinDelete(int IzinBilgisiId)
        {
            var delete = _context.Izinler.Find(IzinBilgisiId);

            var personel = _context.Personels.Find(delete.PersonelId);

            if (personel != null)
            {
                personel.BuYıl = personel.BuYıl+delete.Kullanilanizin;


            }

            _context.Izinler.Remove(delete);
            _context.SaveChanges();
            return RedirectToAction("List");
        }

    }

}

PersonelApp.Web/Views/Personel/Create.cshtml
@model Personel

<form method="post" asp-controller="personel" asp-action="create">
	<div class="row mt-3">
		<div class="col-md-1">
		</div>
		<div class="col-md-10">
		
	<div class="form-group">
		<label asp-for="KimlikNo">KimlikNo</label>
		<input asp-for="KimlikNo" class="form-control" />
		<span asp-validation-for="KimlikNo" class="text-danger"></span>
	</div>

	<div class="form-group">
		<label asp-for="Ad">Ad</label>
		<input asp-for="Ad" class="form-control" />
		<span asp-validation-for="Ad" class="text-danger"></span>
	</div>

	<div class="form-group">
		<label asp-for="Soyad">Soyad</label>
		<input asp-for="Soyad" class="form-control" />
		<span asp-validation-for="Soyad" class="text-danger"></span>
	</div>

	<div class="form-group">
		<label asp-for="Zaman">Zaman</label>
				<input asp-for="Zaman" class="form-control" type="date" />
		<span asp-validation-for="Zaman" class="text-danger"></span>
	</div>

	<div class="row mt-3 ">

		<div class="col-md-4 ">
			<select asp-for="FakulteId" asp-items="@ViewBag.Fakultes" class="form-select" size="7" aria-label="Size 7 select example">
				<option selected disabled>Fakülte Seçiniz</option>
			</select>
			<span asp-validation-for="FakulteId" class="text-danger"></span>
		</div>
		<div class="col-md-4 ">
			<select asp-for="BolumId" asp-items="@ViewBag.Bolums" class="form-select" size="7" aria-label="Size 7 select example">
				<option selected disabled>Bölüm Seçiniz</option>
			</select>
			<span asp-validation-for="BolumId" class="text-danger"></span>
		</div><div class="col-md-4 ">
			<select asp-for="AbdId" asp-items="@ViewBag.Abds" class="form-select" size="7" aria-label="Size 7 select example">
				<option selected disabled>Fakülte Seçiniz</option>
			</select>
			<span asp-validation-for="AbdId" class="text-danger"></span>
		</div>
	</div>
			<div class="d-grid gap-2 mt-3 justify-content-center">
				<button type="submit" class="btn btn-primary">Submit</button>
			</div>

</form>



		

PersonelApp.Web/Views/Personel/Edit.cshtml
@model Personel

<form method="post" asp-controller="personel" asp-action="Edit">
	<input type="hidden" name="PersonelId" value="@Model.PersonelId" />
	<div class="row mt-3">
		<div class="col-md-1">
		</div>
		<div class="col-md-10">

			<div class="form-group">
				<label asp-for="Ad">Ad</label>
				<input asp-for="Ad" class="form-control" value="@Model.Ad" />
				<span asp-validation-for="Ad" class="text-danger"></span>
			</div>

			<div class="form-group">
				<label asp-for="Soyad">Soyad</label>
				<input asp-for="Soyad" class="form-control" value="@Model.Soyad" />
				<span asp-validation-for="Soyad" class="text-danger"></span>
			</div>

			<div class="form-group">
				<label asp-for="GecenYıl">@(DateOnly.FromDateTime(DateTime.Today).Year-1) Yılına ait yıllık izin</label>
				<input asp-for="GecenYıl" class="form-control" value="@Model.GecenYıl" />
				<span asp-validation-for="GecenYıl" class="text-danger"></span>
			</div>

			<div class="form-group">
				<label asp-for="BuYıl">@DateOnly.FromDateTime(DateTime.Today).Year Yılına ait yıllık izin</label>
				<input asp-for="BuYıl" class="form-control" value="@Model.BuYıl" />
				<span asp-validation-for="BuYıl" class="text-danger"></span>
			</div>

			

			<div class="d-grid gap-2 mt-3 justify-content-center">
				<button type="submit" class="btn btn-primary">Submit</button>
			</div>
		</div>
		<div class="col-md-1">
		</div>
	</div>
</form>

PersonelApp.Web/Views/Personel/EditFGY.cshtml
@model FGYEditViewModel

<form method="post" asp-controller="personel" asp-action="EditFGY">
	<input type="hidden" name="PersonelId" value="@Model.PersonelId" />
	<div class="row mt-3">
		<div class="col-md-1">
		</div>
		<div class="col-md-10">
			<div class="row mt-3 ">

				<div class="col-md-4 ">
					<select asp-for="FakulteId" asp-items="@ViewBag.Fakultes" class="form-select" size="7" aria-label="Size 7 select example">
						<option selected disabled>Fakülte Seçiniz</option>
					</select>
					<span asp-validation-for="FakulteId" class="text-danger"></span>
				</div>
				<div class="col-md-4 ">
					<select asp-for="BolumId" asp-items="@ViewBag.Bolums" class="form-select" size="7" aria-label="Size 7 select example">
						<option selected disabled>Bölüm Seçiniz</option>
					</select>
					<span asp-validation-for="BolumId" class="text-danger"></span>
				</div><div class="col-md-4 ">
					<select asp-for="AbdId" asp-items="@ViewBag.Abds" class="form-select" size="7" aria-label="Size 7 select example">
						<option selected disabled>Fakülte Seçiniz</option>
					</select>
					<span asp-validation-for="AbdId" class="text-danger"></span>
				</div>
			</div>

			<div class="d-grid gap-2 mt-3 justify-content-center">
				<button type="submit" class="btn btn-primary">Submit</button>
			</div>
		</div>
		<div class="col-md-1">
		</div>
	</div>
</form>

PersonelApp.Web/Views/Personel/IzinForm.cshtml
@model IzinBilgisi

<form method="post" asp-controller="Personel" asp-action="IzinForm">

<input type="hidden" name="PersonelId" value="@Model.PersonelId" />
	<div class="form-group">
		<label asp-for="BaslangicTarihi">BaslangicTarihi</label>
		<input asp-for="BaslangicTarihi" class="form-control" type="date"/>
		<span asp-validation-for="BaslangicTarihi" class="text-danger"></span>
	</div>

	<div class="form-group">
		<label asp-for="BitisTarihi">BitisTarihi</label>
		<input asp-for="BitisTarihi" class="form-control" type="date" />
		<span asp-validation-for="BitisTarihi" class="text-danger"></span>
	</div>
	<div class="d-grid gap-2 mt-3 justify-content-center">
		<button type="submit" class="btn btn-primary">Submit</button>
	</div>
	

</form>

PersonelApp.Web/Views/Personel/Izinler.cshtml
@model IzinViewModel

@if (TempData["Message"] != null)
{
    @section message {
    @await Html.PartialAsync("_message", (string)TempData["Message"])
}
}

<div class="row mt-3">
    <div class="col-md-1">
    </div>
    <div class="col-md-10">

        @foreach (var item in Model.Izinler.Join(Model.Personels, p => p.PersonelId, z => z.PersonelId, (p,z) => new {p,z}))
        {
            <div class="card mb-3 mt-3" style="max-width: auto;">
                <div class="row no-gutters">
                    <div class="col-md-1">
                    </div>
                    <div class="col-md-11">
                        <div class="card-body">
                            <h7 class="card-title"><b>Sicil No:</b> @item.z.PersonelId</h7><hr />
                            <h7 class="card-title"><b>Ad Soyad:</b> @(item.z.Ad + " " + item.z.Soyad)</h7><hr />
                            <h7 class="card-title"><b>İzin Başlangıç Tarihi:</b> @item.p.BaslangicTarihi</h7><hr />
                            <h7 class="card-title"><b>İzin Bitiş Tarihi:</b> @item.p.BitisTarihi</h7><hr />
                            <h7 class="card-title"><b>Kullanılan İzin:</b> @item.p.Kullanilanizin</h7><hr />
                            <form asp-controller="personel" asp-action="IzinDelete" method="post" style="display:inline">
                                <input type="hidden" name="IzinBilgisiId" value="@item.p.IzinBilgisiId" />
                                <button type="submit" class="btn btn-danger">Sil</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

        }
    </div>
    <div class="col-md-1">
        
    </div>
</div>

PersonelApp.Web/Views/Personel/List.cshtml
@model PersonelsViewModel

<div class="row mt-3">
    
    <div class="col-md-3">
        
    </div>
    <div class="col-md-6">
        <form class="d-flex" role="search" action="/personel/list" method="get">
            <input class="form-control me-2" type="text" placeholder="Personel Ara" aria-label="Search" name="q"/>
            <button class="btn btn-outline-success" type="submit">Bul</button>
        </form>
    </div>
    <div class="col-md-3">
    </div>
</div>


@if (TempData["Message"] != null)
{
    @section message {
    @await Html.PartialAsync("_message", (string)TempData["Message"])
}
}




<div class="row mt-3">

    <div class="col-md-1">
    </div>
    <div class="col-md-10">
        @foreach (var personel in Model.personels)
        {


            <div class="card mb-3" style="max-width: auto;">
                <div class="row g-0">
                    <div class="col-md-2">
                        <img src="..." class="img-fluid rounded-start" alt="...">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title">@personel.PersonelId</h5>
                            <h5 class="card-title">@(personel.Ad + " " + personel.Soyad)</h5>
                            <p class="card-text">TC: @personel.KimlikNo</p>
                            <p class="card-text">İşe Başlama Tarihi: @personel.Zaman</p>
                            <p class="card-text">Yıllık İzin: @(personel.GecenYıl + personel.BuYıl)</p>
                            <a type="button" class="btn btn-warning" asp-controller="personel" asp-action="IzinForm" asp-route-id="@personel.PersonelId">İzin Gir</a>
                            <a type="button" class="btn btn-warning" asp-controller="personel" asp-action="Edit" asp-route-id="@personel.PersonelId">Düzenle</a>
                            <a type="button" class="btn btn-warning" asp-controller="personel" asp-action="EditFGY" asp-route-id="@personel.PersonelId">FGY Düzenle</a>

                            <form asp-controller="personel" asp-action="Delete" method="post" style="display:inline">
                                <input type="hidden" name="PersonelId" value="@personel.PersonelId" />
                                <button type="submit" class="btn btn-danger">Sil</button>
                            </form>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <p><b>Fakülte: </b>@personel.Fakulte.FakulteName<hr /><b>Bölüm: </b>@personel.Bolum.BolumName<hr /><b>Abd: </b>@personel.Abd.AbdName</p>
                    </div>
                   

                </div>
            </div>

        }


    </div>
    <div class="col-md-1">
    </div>
</div>

PersonelApp.Web/Views/Personel/Update.cshtml
<h1 class="nav justify-content-center">01 Ocak tarihinde yıllık izinleri güncellemek için tıkla</h1>
<form method="post" asp-controller="Personel" asp-action="Update">
	<div class="d-grid gap-2 mt-3 justify-content-center">
		<button type="submit" class="btn btn-primary">Güncelle</button>
	</div>

	

</form>